# User Settings | Edit there as per required

title: binaryoverload
url: "http://binaryoverload.co.uk"

# This will show up at the top of index page
site_heading: >
    binaryoverload<span class="faded">'s</span> <span class="faded">blog</span>

email: wegg7250@gmail.com
author: William Oldham
# This description will show up in google search results
# (for index page) etc.
description: >
    It's just me, you and whoever is listening to your internet connection!

# This will what will show against &copy; in the footer
copyright: BinaryOverload
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! 

permalink: pretty

# Comments are powered by disqus
comments: true
disqus_short_name: binaryoverload-1

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Tech enthusiast, amatateur photographer and a guy that says random stuff on the internet sometimes

about_footer: true

twitter_username: binary_overload
github_username: binaryoverload

favicon: true
favicon_location: "/images/favicon.ico"

profile_picture: /images/profile-picture.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-133832664-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.com/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
